
[General]
	#Add Only Silver items to chest loot?
	AddModLootToChests = true
	#Can build silver golems?
	BuildSilverGolem = true

["Ore Generation"]
	#Silver ore vein count per chunk
	#Range: > 0
	SilverVeinCount = 8
	#Silver ore vein size
	#Range: > 0
	SilverVeinSize = 5
	#Enable silver ore generation?
	EnableSilverOre = true
	#Silver ore minimum height
	#Range: 1 ~ 255
	SilverBottomHeight = 1
	#Silver ore maximum height
	#Range: 1 ~ 255
	SilverMaxHeight = 42

[Enchantments]
	#Enable Incantation enchantment?
	EnableIncantation = true
	#Everlasting Enchantment enabled?
	EnableSilverAura = true

